<h1><center>Laboratorio 8: Aprendizaje Supervisado 🔮</center></h1>

<center><strong>MDS7202: Laboratorio de Programación Científica para Ciencia de Datos</strong></center>

### Cuerpo Docente:

- Profesor: Ignacio Meza y Gabriel Iturra
- Auxiliar: Sebastián Tinoco
- Ayudante: Arturo Lazcano y Angelo Muñoz

### Equipo: SUPER IMPORTANTE - notebooks sin nombre no serán revisados

- Nombre de alumno 1: Tomás Aguirre
- Nombre de alumno 2: Ignacio Albornoz


### **Link de repositorio de GitHub:** https://github.com/tomasaguirre-ignacioalbornoz/MDS7202/tree/main

## Temas a tratar

- Aprendizaje Supervisado
- Flujos de datos a través de `Pipelines`.

## Reglas

- **Grupos de 2 personas**
- Asistencia **obligatoria** a instrucciones del lab (viernes 16.15). Luego, pueden quedarse trabajando en las salas o irse.
- **No se revisarán entregas de personas ausentes**. 
- Cualquier duda fuera del horario de clases al foro. Mensajes al equipo docente serán respondidos por este medio.
- Prohibidas las copias. 
- Pueden usar cualquer matrial del curso que estimen conveniente.

## Objetivos principales del laboratorio

- Comprender el funcionamiento de clasificadores/regresores.
- Generar múltiples modelos predictivos.
- Comprender las ventajas de crear modelos en pipeline vs hacer las operaciones a mano.

El laboratorio deberá ser desarrollado sin el uso indiscriminado de iteradores nativos de python (aka "for", "while"). La idea es que aprendan a exprimir al máximo las funciones optimizadas que nos entrega `pandas`, las cuales vale mencionar, son bastante más eficientes que los iteradores nativos sobre `DataFrames`.

### Importamos librerias utiles 😸

In [121]:
# Libreria Core del lab.
import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split 

# Pre-procesamiento
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import FunctionTransformer
from sklearn.preprocessing import PowerTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.tree import DecisionTreeClassifier

# Metricas de evaluación
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import cohen_kappa_score

#Libreria para plotear
!pip install --upgrade plotly
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go

https://www.kaggle.com/antoinekrajnc/soccer-players-statistics

# 1. Predicciones Futboleras

<p align="center">
  <img src="https://drive.google.com/uc?export=view&id=1BnO4tyh3vM2P199Ec9s3JjngQ4qQ9seP"
" width="300">
</p>


Tras el trágico despido de la mítica mascota de Maipú, Renacín decide adentrarse como consultor en el mercado futbolero, el cuál (para variar...) está cargado en especulaciones. 

Como su principal tarea será asesorar a los directivos de los clubes sobre cuál jugador comprar y cuál no, Renacín desea generar modelos predictivos que evaluén distintas características de los jugadores; todo con el fin de tomar decisiones concretas basadas en los datos.

Sin embargo, su condición de corporeo le impidió tomar la versión anterior de MDS7202, por lo que este motivo Renacín contrata a su equipo para lograr su objetivo final. Dado que aún tiene fuertes vínculos con la dirección de deportes de la municipalidad, el corporeo le entrega base de datos con las estadísticas de cada jugador para que su equipo empieze a trabajar ya con un dataset listo para ser usado.


**Los Datos**

Para este laboratorio deberán trabajar con los csv `statsplayers.csv` y `salarios.csv`, donde deberán aplicar algoritmos de de aprendizaje supervisado (clasificación y regresión) en base a características que describen de jugadores de futbol.

Para comenzar cargue el dataset señalado y a continuación vea el reporte **`Player_Stats_Report.html`** (adjunto en la carpeta del enunciado) que describe las características principales del `DataFrame`.

In [122]:
# Si usted está utilizando Colabolatory le puede ser útil este código para cargar los archivos.
try:
    from google.colab import drive
    drive.mount("/content/drive")
    path = 'Dirección donde tiene los archivos en el Drive'
except: 
    print('Ignorando conexión drive-colab')

Ignorando conexión drive-colab


In [123]:
df_players = pd.read_csv('stats_players.csv')
df_players

Name          Nationality National_Position Club_Position  \
0      Cristiano Ronaldo             Portugal                LS            LW   
1           Lionel Messi            Argentina                RW            RW   
2                 Neymar               Brazil                LW            LW   
3            Luis Suárez              Uruguay                LS            ST   
4           Manuel Neuer              Germany                GK            GK   
...                  ...                  ...               ...           ...   
17583        Adam Dunbar  Republic of Ireland               NaN           Sub   
17584       Dylan McGoey  Republic of Ireland               NaN           Sub   
17585    Tommy Ouldridge              England               NaN           Res   
17586         Mark Foden             Scotland               NaN           Sub   
17587   Barry Richardson              England               NaN           Sub   

       Height  Weight Preffered_Foot  Age        Work_Rate  Weak_foot  \
0         185      80          Right   32       High / Low          4   
1         170      72           Left   29  Medium / Medium          4   
2         174      68          Right   25    High / Medium          5   
3         182      85          Right   30    High / Medium          4   
4         193      92          Right   31  Medium / Medium          4   
...       ...     ...            ...  ...              ...        ...   
17583     183      82          Right   19  Medium / Medium          1   
17584     185      80          Right   19  Medium / Medium          2   
17585     173      61          Right   18    High / Medium          2   
17586     180      80          Right   21  Medium / Medium          3   
17587     185      77          Right   47  Medium / Medium          2   

       Skill_Moves  Ball_Control  Dribbling  Marking  Sliding_Tackle  \
0                5            93         92       22              23   
1                4            95         97       13              26   
2                5            95         96       21              33   
3                4            91         86       30              38   
4                1            48         30       10              11   
...            ...           ...        ...      ...             ...   
17583            1            12         11       12              12   
17584            1            13         11       11              12   
17585            2            44         39       40              29   
17586            1            17         13       11              11   
17587            1            22         11       14              13   

       Standing_Tackle  Aggression  Reactions  Interceptions  Vision  \
0                   31          63         96             29      85   
1                   28          48         95             22      90   
2                   24          56         88             36      80   
3                   45          78         93             41      84   
4                   10          29         85             30      70   
...                ...         ...        ...            ...     ...   
17583               13          25         48             12      37   
17584               11          15         43             12      27   
17585               35          44         42             38      41   
17586               14          23         46             12      13   
17587               12          44         38             16      17   

       Composure  Crossing  Short_Pass  Long_Pass  Acceleration  Speed  \
0             86        84          83         77            91     92   
1             94        77          88         87            92     87   
2             80        75          81         75            93     90   
3             83        77          83         64            88     77   
4             70        15          55         59            58     61

## 1.1 Predicción de Seleccionados Nacionales 

Como primera tarea, Renacín, intrigado por la posibilidad de saber qué tan reconocido es un jugador, le consulta a su equipo si es posible predecir si un jugador será o no seleccionado nacional a partir de sus estadísticas en el juego. 

<p align="center">
  <img src="https://thumbs.gfycat.com/ThornyFrankFoxhound-size_restricted.gif" width="500">
</p>

### 1.1.1 Generación de Labels para la Clasificación [Sin Puntaje]


Primero comience generando las labels para la clasificación. Para esto, trabaje sobre el atributo ```National_Position``` suponiendo que los valores nulos son jugadores no seleccionados para representar a su país. 

Hecho esto, ¿Cuantos ejemplos por cada clase se tienen? Comente lo que observa.



**Respuesta:**

In [124]:
### Código aquí ###
pd.set_option('display.max_columns', None)

df_players['Seleccionado'] = df_players['National_Position'].notnull().astype(int)


In [125]:
df_players['Seleccionado'].value_counts()

0    16513
1     1075
Name: Seleccionado, dtype: int64

Dados los datos de la columna generada que considera como seleccionados nacionales a aquellos jugadores que tienen un valor distinto de nulo en la columna 'National_Position', se tiene que existen 1075 jugadores seleccionados nacionales en el dataset, mientras que los no seleccionados ascienden hasta los 16513.

### 1.1.2 Camino a la clasificación [1 punto]

<p align="center">
  <img src="https://c.tenor.com/SoXZJHWnhKAAAAAC/pitbull-medel.gif" width="500">
</p>

Para preprocesar el dataset, genere un `ColumnTransformer` en donde especifique las transformaciones que hay que realizar para cada columna (por ejemplo StandarScaler, MinMaxScaler, OneHotEncoder, etc...) para que puedan ser utilizadas correctamente por el modelo predictivo y guardelo en algúna variable.

Luego, comente y justifique las transformaciones elegidas sobre cada una de las variables (para esto utilice el material ```Player_Stats_Report.html``` que viene en el zip del lab), al igual que las transformaciones aplicadas.

Hecho lo anterior, **defina al menos 3 pipelines para la clasificación**, en donde utilice el mismo ColumnTransformer definido anteriormente, pero que varie entre cada pipeline los clasificadores. 

Para seleccionar los clasificadores más adecuados, utilice la siguiente guía:

<p align="center">
  <img src="https://scikit-learn.org/stable/_static/ml_map.png" width="500">
</p>

<br/>

Con ella, comente y justifique cada una de las decisiones tomadas al momento de desarrollar su pipeline.

**Nota:** Si tiene problemas al utilizar OneHotEncoder puede utilizar el parámetro handle_unknown='ignore'. Esto hace que en la codificación se omitan las categorias que no aparecen en el entrenamiento. Pregunta dudosa (no tiene puntaje), ¿esto tiene sentido a nivel de modelos?.

**To-Do:**

- [ ] Genere un ```ColumnTransformer``` enfocado en preprocesar los datos.
- [ ] Indicar y Justificar que preprocesamiento utiliza sobre cada columna.
- [ ] Crear 3 ``pipelines`` con diferentes clasificadores.
- [ ] Para seleccionar los clasificadores base sus decisiones en la siguiente [guía](https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html)
- [ ] No entrenar los ``pipelines`` aún.

**Nota:** No es necesario entrenar los clasificadores aún.

Para llegar a los clasificadores a partir de la guía mostrada en el enunciado, se parte con que se tienen más de 50 datos, luego sí se quiere predecir una categoría (seleccionado o no seleccionado). Después se tienen los datos etiquetados y son menos de 100mil, por lo que se prueba con SVC lineal. Como este no entrega buenos resultados, y los datos no son texto, se prueba con Kneighbors, que como tampoco funciona bien, se procede a probar con Random Forest, que es uno de los clasificadores del grupo de Ensemble Classifiers.

In [126]:
df_players.head()

Name Nationality National_Position Club_Position  Height  \
0  Cristiano Ronaldo    Portugal                LS            LW     185   
1       Lionel Messi   Argentina                RW            RW     170   
2             Neymar      Brazil                LW            LW     174   
3        Luis Suárez     Uruguay                LS            ST     182   
4       Manuel Neuer     Germany                GK            GK     193   

   Weight Preffered_Foot  Age        Work_Rate  Weak_foot  Skill_Moves  \
0      80          Right   32       High / Low          4            5   
1      72           Left   29  Medium / Medium          4            4   
2      68          Right   25    High / Medium          5            5   
3      85          Right   30    High / Medium          4            4   
4      92          Right   31  Medium / Medium          4            1   

   Ball_Control  Dribbling  Marking  Sliding_Tackle  Standing_Tackle  \
0            93         92       22              23               31   
1            95         97       13              26               28   
2            95         96       21              33               24   
3            91         86       30              38               45   
4            48         30       10              11               10   

   Aggression  Reactions  Interceptions  Vision  Composure  Crossing  \
0          63         96             29      85         86        84   
1          48         95             22      90         94        77   
2          56         88             36      80         80        75   
3          78         93             41      84         83        77   
4          29         85             30      70         70        15   

   Short_Pass  Long_Pass  Acceleration  Speed  Stamina  Strength  Balance  \
0          83         77            91     92       92        80       63   
1          88         87            92     87       74        59       95   
2          81         75            93     90       79        49       82   
3          83         64            88     77       89        76       60   
4          55         59            58     61       44        83       35   

   Agility  Jumping  Heading  Shot_Power  Finishing  Long_Shots  Curve  \
0       90       95       85          92         93          90     81   
1       90       68       71          85         95          88     89   
2       96       61       62          78         89          77     79   
3       86       69       77          87         94          86     86   
4       52       78       25          25         13          16     14   

   Freekick_Accuracy  Penalties  Volleys  Seleccionado  
0                 76         85       88             1  
1                 90         74       85             1  
2                 84         81       83             1  
3                 84         85       88             1  
4                 11         47       11             1

**Respuesta:**

In [127]:
df_players.drop(['National_Position', 'Nationality', 'Name'], axis=1, inplace=True)

categorical_columns = ['Club_Position', 'Preffered_Foot', 'Work_Rate']
numeric_columns = [
    'Height', 'Weight', 'Age', 'Weak_foot', 'Skill_Moves', 'Ball_Control', 'Dribbling', 'Marking', 'Sliding_Tackle',
    'Standing_Tackle', 'Aggression', 'Reactions', 'Interceptions', 'Vision', 'Composure', 'Crossing', 'Short_Pass',
    'Long_Pass', 'Acceleration', 'Speed', 'Stamina', 'Strength', 'Balance', 'Agility', 'Jumping', 'Heading',
    'Shot_Power', 'Finishing', 'Long_Shots', 'Curve', 'Freekick_Accuracy', 'Penalties', 'Volleys'
]


ct = ColumnTransformer(transformers=[
    ('onehot', OneHotEncoder(), categorical_columns),  
    ('scaler', MinMaxScaler(), numeric_columns)  
], remainder='passthrough')

In [128]:
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

# Define el pipeline para SVC
svc_pipeline = Pipeline([
    ('preprocessor', ct),  
    ('classifier', SVC(kernel='linear'))  
])

# Define el pipeline para K-Nearest Neighbors 
knn_pipeline = Pipeline([
    ('preprocessor', ct),  
    ('classifier', KNeighborsClassifier(n_neighbors=5))  
])

# Define el pipeline para RandomForest
rf_pipeline = Pipeline([
    ('preprocessor', ct),  
    ('classifier', RandomForestClassifier(n_estimators=100, random_state=314159))  
])


### 1.1.3 Entrenemos los pipelines [1 punto]

<p align="center">
  <img src="https://i.gifer.com/7Cc8.gif" width="350">
</p>


Ahora, entrene los `pipeline` generados en los pasos anteriores. Para esto, primero separe los datos de entrenamiento en un conjunto de entrenamiento y de prueba  (la proporción queda a su juicio).

En este paso, seleccione los ejemplos de forma aleatoria e intente mantener la distribución original de labels de cada clase en los conjuntos de prueba/entrenamiento. (vea la documentación de `train_test_split`).


Luego, entrene los pipelines

Una vez entrenado su modelo, evalue su rendimiento a través de diferentes métricas, comentando que significa cada uno de los valores obtenidos. Puede usar la función `classification_report` para corroborar sus resultados.

- ¿Qué implican los valores de accuracy, precisión y recall de la clase positiva (la que indica que un jugador es seleccionado nacional)?
- ¿Podrían mejorarse los resultados?, ¿Cómo?
- ¿Influye la cantidad de ejemplos por clase?

**To-Do**:

- [ ] Separar el conjunto de datos en entrenamiento y de prueba.
- [ ] Entrenar los `pipelines`.
- [ ] Utilizar las métricas para evaluar los modelos generados.


**Respuesta:**

In [129]:
df_players


Club_Position  Height  Weight Preffered_Foot  Age        Work_Rate  \
0                LW     185      80          Right   32       High / Low   
1                RW     170      72           Left   29  Medium / Medium   
2                LW     174      68          Right   25    High / Medium   
3                ST     182      85          Right   30    High / Medium   
4                GK     193      92          Right   31  Medium / Medium   
...             ...     ...     ...            ...  ...              ...   
17583           Sub     183      82          Right   19  Medium / Medium   
17584           Sub     185      80          Right   19  Medium / Medium   
17585           Res     173      61          Right   18    High / Medium   
17586           Sub     180      80          Right   21  Medium / Medium   
17587           Sub     185      77          Right   47  Medium / Medium   

       Weak_foot  Skill_Moves  Ball_Control  Dribbling  Marking  \
0              4            5            93         92       22   
1              4            4            95         97       13   
2              5            5            95         96       21   
3              4            4            91         86       30   
4              4            1            48         30       10   
...          ...          ...           ...        ...      ...   
17583          1            1            12         11       12   
17584          2            1            13         11       11   
17585          2            2            44         39       40   
17586          3            1            17         13       11   
17587          2            1            22         11       14   

       Sliding_Tackle  Standing_Tackle  Aggression  Reactions  Interceptions  \
0                  23               31          63         96             29   
1                  26               28          48         95             22   
2                  33               24          56         88             36   
3                  38               45          78         93             41   
4                  11               10          29         85             30   
...               ...              ...         ...        ...            ...   
17583              12               13          25         48             12   
17584              12               11          15         43             12   
17585              29               35          44         42             38   
17586              11               14          23         46             12   
17587              13               12          44         38             16   

       Vision  Composure  Crossing  Short_Pass  Long_Pass  Acceleration  \
0          85         86        84          83         77            91   
1          90         94        77          88         87            92   
2          80         80        75          81         75            93   
3          84         83        77          83         64            88   
4          70         70        15          55         59            58   
...       ...        ...       ...         ...        ...           ...   
17583      37         35        12          22         19            25   
17584      27         22        14          27         26            16   
17585      41         35        35          48         42            62   
17586      13         28        15          20         15            42   
17587      17         44        11          12         13            25   

       Speed  Stamina  Strength  Balance  Agility  Jumping  Heading  \
0         92       92        80       63       90       95       85   
1         87       74        59       95       90       68       71   
2         90       79        49       82       96       61       62   
3         77       89        76       60       86       69       77   
4         61       44        83       35       52       78       25   


In [130]:
X = df_players.drop('Seleccionado', axis = 1)
y = df_players['Seleccionado']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=314159, stratify=y)

In [131]:
# Entrena el pipeline para SVC lineal
svc_pipeline.fit(X_train, y_train)

# Entrena el pipeline para K-Nearest Neighbors
knn_pipeline.fit(X_train, y_train)

# Entrena el pipeline para RandomForestClassifier
rf_pipeline.fit(X_train, y_train)


Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehot', OneHotEncoder(),
                                                  ['Club_Position',
                                                   'Preffered_Foot',
                                                   'Work_Rate']),
                                                 ('scaler', MinMaxScaler(),
                                                  ['Height', 'Weight', 'Age',
                                                   'Weak_foot', 'Skill_Moves',
                                                   'Ball_Control', 'Dribbling',
                                                   'Marking', 'Sliding_Tackle',
                                                   'Standing_Tackle',
                                                   'Aggression', 'Reactions',
                                                   'Interceptions', 'Vision',
                                                   'Composure', 'Crossing',
                                                   'Short_Pass', 'Long_Pass',
                                                   'Acceleration', 'Speed',
                                                   'Stamina', 'Strength',
                                                   'Balance', 'Agility',
                                                   'Jumping', 'Heading',
                                                   'Shot_Power', 'Finishing',
                                                   'Long_Shots', 'Curve', ...])])),
                ('classifier', RandomForestClassifier(random_state=314159))])

In [132]:
# Hacer predicciones en los datos de prueba.
y_pred_svc = svc_pipeline.predict(X_test)
y_pred_knn = knn_pipeline.predict(X_test)
y_pred_rf = rf_pipeline.predict(X_test)

# Calcular el informe de clasificación para cada modelo.
report_svc = classification_report(y_test, y_pred_svc)
report_knn = classification_report(y_test, y_pred_knn)
report_rf = classification_report(y_test, y_pred_rf)

# Imprimir los informes de clasificación.
print("Classification Report for SVC Pipeline:")
print(report_svc)

print("Classification Report for K-Nearest Neighbors Pipeline:")
print(report_knn)

print("Classification Report for Random Forest Pipeline:")
print(report_rf)

Classification Report for SVC Pipeline:
              precision    recall  f1-score   support

           0       0.94      1.00      0.97      1651
           1       0.00      0.00      0.00       108

    accuracy                           0.94      1759
   macro avg       0.47      0.50      0.48      1759
weighted avg       0.88      0.94      0.91      1759

Classification Report for K-Nearest Neighbors Pipeline:
              precision    recall  f1-score   support

           0       0.94      1.00      0.97      1651
           1       0.50      0.06      0.10       108

    accuracy                           0.94      1759
   macro avg       0.72      0.53      0.53      1759
weighted avg       0.91      0.94      0.91      1759

Classification Report for Random Forest Pipeline:
              precision    recall  f1-score   support

           0       0.94      1.00      0.97      1651
           1       0.67      0.09      0.16       108

    accuracy                        

c:\Users\tomas\anaconda3\envs\Lab_6\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\tomas\anaconda3\envs\Lab_6\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\tomas\anaconda3\envs\Lab_6\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


**Respuesta**:
- ¿Qué implican los valores de accuracy, precisión y recall de la clase positiva (la que indica que un jugador es seleccionado nacional)?
- ¿Podrían mejorarse los resultados?, ¿Cómo?
- ¿Influye la cantidad de ejemplos por clase?
```
En primer lugar el valor de accuracy indica la proporción de predicciones correctas sobre el total de predicciones del modelo para clasificar las clases. En este caso, el accuracy de los tres modelos es de 0.94. Esto porque si bien se obtienen buenas métricas para los jugadores que no son seleccionados y malas para aquellos que sí lo son, dado que el número de muestras de la clase de no seleccionados es mucho mayor que la de selecccionados, entonces se hace un efecto invisibilizador de la clase mayoritaria sobre la minoritaria.
En segundo lugar, el valor de precisión indica la proporción de verdaderos positivos y el número total de valores clasificados como positivos. Aquí, para la clase negativa se obtiene un valor de 0.94 en todos los modelos, mientras que para la clase positiva se obtiene un 0 en SVC lineal, 0.5 en Kneighbors y 0.67 en RandomForest. Estos no son buenos resultados, pues indican que en SVC lineal 0 de las muestras clasificadas como positivas eran realmente positivas. Por otro lado, Kneighbors indica que el 50% de las muestras clasificadas como positivas eran realmente positivas. Y finalmente, en Random Forest solo el 67% de las muestras clasificadas como positivas son realmente positivas.
Por último, el valor de recall indica la proporción de verdaderos positivos que son correctamente clasificados sobre todos los valores que son positivos. En este sentido, nuevamente el valor obtenido por SVC lineal es de 0. Luego el valor de Kneighbors es de 0.06, y finalmente el de Random Forest es de 0.09. Esto significa que muchos de los jugadores seleccionados no se están identificando correctamente.

Existen muchas formas de mejorar estos resultados. 

En primer lugar, se podría obtener más datos, especialmente de la clase positiva, de manera que los datos se encuentren más balanceados. Por otro lado, se podrían aplicar técnicas de oversampling que ayuden a balancear las clases, ya que el que la clase positiva tenga tantos menos valores que la clase negativa no permite que el modelo pueda obtener la información suficiente de la clase minoritaria.
Con respecto a los modelos, se podría explorar el ajuste de los hiperparámetres de los algoritmos de manera que se ajusten mejor a los datos que se tienen. Además, existen otros modelos dentro de ensemble learning que podrían utilizarse para intentar obtener mejores métricas.

```

## 1.2 Predicción de posiciones de jugadores [2 puntos]

<p align="center">
  <img src="https://pbs.twimg.com/media/E1rfA1aWEAYU6Ny.jpg" width="500">
</p>

En una nueva jornada de desmesuradas transacciones deportivas, Renacín escuchó a sus colegas discutir acerca de que el precio de cada jugador depende en gran medida de la posición en la cancha en la que juega. Y además, que hay bastantes jugadores nuevos que no tienen muy claro en que posición verdaderamente brillarían, por lo que actualmente puede que actualmente estén jugando en posiciones sub-optimas. 

Viendo que los resultados del primer análisis no son tan esperanzadores, el corporeo los comanda a cambiar su tarea: ahora, les solicita que construyan un clasificador enfocado en predecir la mejor posición de los jugadores en la cancha según sus características. 

Para lograr esto, primero, les pide que etiqueten de la siguiente manera los valores que aparecen en el atributo ```Club_Position```, pidiendo que agrupen los valores en los siguientes grupos:

**Nota**:  Renacín les recalca que **no deben utilizar los valores ```Sub``` y ```Res``` de esta columna**.

```python
ataque = ['ST', 'CF'] 
central_ataque = ['RW', 'CAM', 'LW'] 
central = ['RM', 'CM', 'LM'] 
central_defensa = ['RWB', 'CDM', 'LWB']
defensa = ['RB', 'CB', 'LB']
arquero = ['GK']
```

Cabe señalar que al igual como lo realizado con la clasificación binaria, deberá justificar en base a la [guía](https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html) la elección del clasificador y se deben comentar los resultados obtenidos en la clasificación.

**Nota:** Clasifique solamente con las clases señaladas, si observa mas clases eliminelas de la clasficación.

**To-Do**:

- [ ] Aplique las etiquetas descritas anteriormente en cada uno de los valores señalados en esta sección.
- [ ] Cuente cuantos por clase quedan.
- [ ] Entrene el nuevo pipeline y ejecute una evaluación de este.  
- [ ] Comente los resultados obtenidos.

**Respuesta:**

In [134]:
df_players = pd.read_csv('stats_players.csv')

In [135]:
# Define los grupos de etiquetas.
ataque = ['ST', 'CF']
central_ataque = ['RW', 'CAM', 'LW']
central = ['RM', 'CM', 'LM']
central_defensa = ['RWB', 'CDM', 'LWB']
defensa = ['RB', 'CB', 'LB']
arquero = ['GK']

# Crea una nueva columna 'Club_Position_Group' con las etiquetas.
df_players['Posicion'] = pd.np.where(df_players['Club_Position'].isin(ataque), 'ataque',
    pd.np.where(df_players['Club_Position'].isin(central_ataque), 'central_ataque',
    pd.np.where(df_players['Club_Position'].isin(central), 'central',
    pd.np.where(df_players['Club_Position'].isin(central_defensa), 'central_defensa',
    pd.np.where(df_players['Club_Position'].isin(defensa), 'defensa',
    pd.np.where(df_players['Club_Position'].isin(arquero), 'arquero', None))))))


C:\Users\tomas\AppData\Local\Temp\ipykernel_7136\1634725381.py:10: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead.
  df_players['Posicion'] = pd.np.where(df_players['Club_Position'].isin(ataque), 'ataque',
C:\Users\tomas\AppData\Local\Temp\ipykernel_7136\1634725381.py:11: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead.
  pd.np.where(df_players['Club_Position'].isin(central_ataque), 'central_ataque',
C:\Users\tomas\AppData\Local\Temp\ipykernel_7136\1634725381.py:12: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead.
  pd.np.where(df_players['Club_Position'].isin(central), 'central',
C:\Users\tomas\AppData\Local\Temp\ipykernel_7136\1634725381.py:13: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a fu

In [136]:
df_players['Posicion'].value_counts()

defensa            1180
central             907
arquero             632
central_ataque      581
ataque              430
central_defensa     209
Name: Posicion, dtype: int64

**Respuesta**:

```
Comente de resultados observados y si es posible mejorar los resultados.
```

## 1.3 Predicción de Sueldos [2 puntos]

<p align="center">
  <img src="https://media.giphy.com/media/3oEjHWtHAFcOKS4iA0/giphy.gif" width="460">
</p>

Queriendo ahondar aún más en el mercado del balompíe, Renacin, logra obtener (de una manera no muy formal) los sueldos de múltiples futbolistas y los guarda en el archivo ```sueldos.csv```. Con ellos les solicita que generen un regresor que les permita predecir el sueldo de los futbolistas en base a las características de los pichichis, esto, debido a su motivación por invertir y/o realizar especulación sobre los sueldos de jugadores.

Renacin es claro señalando que deben seguir utilizando la [guía](https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html) y comenten cada uno de los pasos realizados, para obtener su regresión lineal. Señalándoles que no aceptara un $R^2$ inferior a 0.35 para el modelo solicitado.

Para esta parte usted tiene total libertad en la generación del regresor, la unica exigencia es que utilice un pipeline para generar la regresión y utilice la metrica $R^2$ para medir el rendimiento de esta.

**To-Do**:

- [ ] Explique en que consiste la métrica $R^2$
- [ ] Generar un pipeline para la regresión.
- [ ] Obtener un regresor con un $R^2$ superior a  $0.35$.
- [ ] Comente sus resultados y si es posible mejorar los resultados obtenidos. ¿Se necesitarían más datos o otros tipos de características o una combinación de ambos?

**Respuesta**

In [ ]:
### Código aquí ###

**Respuesta**:

```
Comente de resultados observados y si es posible mejorar los resultados.
```

# Conclusión
Eso ha sido todo para el lab de hoy, recuerden que el laboratorio tiene un plazo de entrega de una semana. Cualquier duda del laboratorio, no duden en contactarnos por mail o U-cursos.

<p align="center">
  <img src="https://media2.giphy.com/media/l1J3CbFgn5o7DGRuE/giphy.gif">
</p>

<br>
<center>
<img src="https://i.kym-cdn.com/photos/images/original/001/194/195/b18.png" width=100 height=50 />
</center>
<br>

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=87110296-876e-426f-b91d-aaf681223468' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>